/*
 * generated by Xtext 2.16.0
 */
package com.statestr.gcth.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class BonanzaWebModule extends AbstractBonanzaWebModule {
}
