/*
 * generated by Xtext 2.16.0
 */
package com.statestr.gcth


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BonanzaStandaloneSetup extends BonanzaStandaloneSetupGenerated {

	def static void doSetup() {
		new BonanzaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
