/*
 * generated by Xtext 2.16.0
 */
package com.statestr.gcth

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BonanzaRuntimeModule extends AbstractBonanzaRuntimeModule {

//	override void configureIScopeProviderDelegate(Binder binder) {
//		binder.bind(IScopeProvider).annotatedWith(Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(
//			BonanzaImportedNamespaceAwareLocalScopeProvider);
//	}
}
