/*
 * generated by Xtext 2.16.0
 */
package com.statestr.gcth.ide

import com.google.inject.Guice
import com.statestr.gcth.BonanzaRuntimeModule
import com.statestr.gcth.BonanzaStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BonanzaIdeSetup extends BonanzaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BonanzaRuntimeModule, new BonanzaIdeModule))
	}
	
}
